fix: remove error when using Python >= 3.11
Make Range immutable by adding __hash__ function. Needed to avoid errors
using Python >= 3.11 triggered by the following change:

  https://docs.python.org/3.11/whatsnew/3.11.html#dataclasses

The specific error one encounters using Python >= 3.11 is:

```
ValueError: mutable default <class 'llvm_diagnostics.messages.Range'> for field column_number is not allowed: use default_factory
```

Alternatively, we could have use default_factory.